[Interface]
PrivateKey = LAPTOP_PRIVATE_KEY
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = SERVER_PUBLIC_KEY
Endpoint = 52.5.XXX.XXXX:51820 #Server ip
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
